# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Ruiming Luo
title: CS Ph.D. Student
email: joeluo@zju.edu.cn
website: https://luoruiming.github.io/

# Social links
github_username:  luoruiming
linkedin_username: luoruiming
# csdn_username: 

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Ruiming Luo and I'm a Ph.D. student at College of Computer Science and Technology, Zhejiang University. My research interests include lower limb exoskeleton, reinforcement learning in Robotics.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in robotics and reinforcement learning, some of my other interests and hobbies are:
   - Basketball
   - Music
   - Hiking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
